# Generated by Django 3.2.20 on 2023-09-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_auto_20221220_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'fleetcare'), ('other', 'Other'), ('fleetcare_error', 'Fleetcare (error)')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='invalidloggedpoint',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'fleetcare'), ('other', 'Other'), ('fleetcare_error', 'Fleetcare (error)')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='loggedpoint',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'fleetcare'), ('other', 'Other'), ('fleetcare_error', 'Fleetcare (error)')], db_index=True, default='other', max_length=32),
        ),
    ]
